paths:
  /products:
    get:
      tags:
        - Products
      summary: Get combined list of cars and properties
      description: Retrieves the latest 10 cars and 10 properties, filtered by query parameters and sorted by creation date.
      parameters:
        - name: brand
          in: query
          description: Filter by car brand
          required: false
          schema:
            type: string
        - name: model
          in: query
          description: Filter by car model
          required: false
          schema:
            type: string
        - name: location
          in: query
          description: Filter by location
          required: false
          schema:
            type: string
        - name: minPrice
          in: query
          description: Minimum price
          required: false
          schema:
            type: number
        - name: maxPrice
          in: query
          description: Maximum price
          required: false
          schema:
            type: number
      responses:
        '200':
          description: A list of mixed products (cars and properties) sorted by created_at
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "تم استرجاع المنتجات بنجاح"
                  data:
                    type: array
                    items:
                      oneOf:
                        - type: object
                          properties:
                            type:
                              type: string
                              enum: [car]
                              example: car
                            data:
                              type: object
                              properties:
                                id:
                                  type: integer
                                title_ar:
                                  type: string
                                title_en:
                                  type: string
                                desc_ar:
                                  type: string
                                desc_en:
                                  type: string
                                images:
                                  type: array
                                  items:
                                    type: string
                                model:
                                  type: string
                                brand:
                                  type: string
                                location:
                                  type: string
                                lat:
                                  type: number
                                  nullable: true
                                long:
                                  type: number
                                  nullable: true
                                status:
                                  type: string
                                isActive:
                                  type: boolean
                                price:
                                  type: number
                                listing_type:
                                  type: string
                                  enum: [sale, rent]
                                seller_type:
                                  type: string
                                  enum: [owner, broker]
                                created_at:
                                  type: string
                                  format: date-time
                                user:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                broker_office:
                                  type: object
                                  nullable: true
                                  properties:
                                    id:
                                      type: integer
                        - type: object
                          properties:
                            type:
                              type: string
                              enum: [property]
                              example: property
                            data:
                              type: object
                              properties:
                                id:
                                  type: integer
                                title_ar:
                                  type: string
                                title_en:
                                  type: string
                                desc_ar:
                                  type: string
                                desc_en:
                                  type: string
                                isActive:
                                  type: boolean
                                location:
                                  type: string
                                images:
                                  type: array
                                  items:
                                    type: string
                                lat:
                                  type: number
                                  nullable: true
                                long:
                                  type: number
                                  nullable: true
                                status:
                                  type: string
                                price:
                                  type: number
                                area:
                                  type: string
                                listing_type:
                                  type: string
                                  enum: [sale, rent]
                                seller_type:
                                  type: string
                                  enum: [owner, broker]
                                created_at:
                                  type: string
                                  format: date-time
                                property_type:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                user:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                broker_office:
                                  type: object
                                  nullable: true
                                  properties:
                                    id:
                                      type: integer
        '500':
          description: Internal server error