openapi: 3.0.0
info:
  title: Property Search API
  description: API for searching properties with various filters
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Development server
tags:
  - name: search property
    description: Operations related to property search
paths:
  /search/properties:
    post:
      tags:
        - search property
      summary: Search properties with advanced filters
      description: Returns a list of properties matching the specified criteria
      operationId: searchProperties
      parameters:
        - $ref: '#/components/parameters/acceptLanguage'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PropertySearchRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PropertySearchResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'

components:
  parameters:
    acceptLanguage:
      name: accept-language
      in: header
      description: Language preference (ar/en)
      schema:
        type: string
        enum: [ar, en]
        default: ar

  schemas:
    PropertySearchRequest:
      type: object
      properties:
        listing_type:
          type: string
          enum: [sale, rent]
          description: Type of listing (sale/rent)
        seller_type:
          type: string
          enum: [owner, broker]
          description: Type of seller (owner/broker)
        property_type_id:
          type: integer
          description: ID of property type
        min_price:
          type: number
          description: Minimum price
        max_price:
          type: number
          description: Maximum price
        min_area:
          type: number
          description: Minimum area
        max_area:
          type: number
          description: Maximum area
        min_floors:
          type: integer
          description: Minimum number of floors
        max_floors:
          type: integer
          description: Maximum number of floors
        location:
          type: string
          description: Location search string
        governorate_id:
          type: number
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/AttributeFilter'
          description: Array of attribute filters
        specifications:
          type: array
          items:
            type: integer
          description: Array of specification IDs to filter by (true values only)
        page:
          type: integer
          default: 1
          description: Page number
        limit:
          type: integer
          default: 20
          description: Number of items per page

    AttributeFilter:
      type: object
      properties:
        attribute_id:
          type: integer
          description: ID of the attribute
        value:
          type: string
          description: Exact value to match
        values:
          type: array
          items:
            type: string
          description: Array of values to match (IN clause)
        min_value:
          type: number
          description: Minimum value (for numeric attributes)
        max_value:
          type: number
          description: Maximum value (for numeric attributes)

    PropertySearchResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/Property'
        message:
          type: string
          description: Response message
        pagination:
          $ref: '#/components/schemas/Pagination'

    Property:
      type: object
      properties:
        id:
          type: integer
        title_ar:
          type: string
        title_en:
          type: string
        desc_ar:
          type: string
        desc_en:
          type: string
        isActive:
          type: boolean
        location:
          type: string
        images:
          type: array
          items:
            type: string
        lat:
          type: number
        long:
          type: number
        price:
          type: number
        area:
          type: number
        floors:
          type: integer
        listing_type:
          type: string
          enum: [sale, rent]
        seller_type:
          type: string
          enum: [owner, broker]
        created_at:
          type: string
          format: date-time
        property_type:
          $ref: '#/components/schemas/PropertyType'
        user:
          $ref: '#/components/schemas/User'

    PropertyType:
      type: object
      properties:
        id:
          type: integer
        name_ar:
          type: string
        name_en:
          type: string

    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string

    Pagination:
      type: object
      properties:
        total:
          type: integer
        page:
          type: integer
        limit:
          type: integer
        totalPages:
          type: integer

    APIError:
      type: object
      properties:
        statusCode:
          type: integer
        message:
          type: string
        timestamp:
          type: string
          format: date-time
        path:
          type: string