openapi: 3.0.0
info:
  title: Property API
  version: 1.0.0
  description: API for managing properties with attributes and specifications.

servers:
  - url: /api

paths:
  /property:
    get:
      summary: Get list of properties
      description: Retrieves properties based on query parameters (e.g., title, location, price).
      tags:
        - property
      parameters:
        - name: title
          in: query
          description: Property title to search for
          required: false
          schema:
            type: string
        - name: location
          in: query
          description: Property location to search for
          required: false
          schema:
            type: string
        - name: minPrice
          in: query
          description: Minimum price filter
          required: false
          schema:
            type: number
            format: float
        - name: maxPrice
          in: query
          description: Maximum price filter
          required: false
          schema:
            type: number
            format: float
        - name: area
          in: query
          description: Property area filter
          required: false
          schema:
            type: string
        - name: listing_type
          in: query
          description: Filter by listing type (sale/rent)
          required: false
          schema:
            type: string
            enum: [sale, rent]
        - name: seller_type
          in: query
          description: Filter by seller type (owner/broker)
          required: false
          schema:
            type: string
            enum: [owner, broker]
        - name: property_type
          in: query
          description: Filter by property type ID
          required: false
          schema:
            type: integer
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Number of items per page for pagination
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Successfully retrieved properties
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title_ar:
                          type: string
                        title_en:
                          type: string
                        desc_ar:
                          type: string
                        desc_en:
                          type: string
                        isActive:
                          type: boolean
                        location:
                          type: string
                        images:
                          type: array
                          items:
                            type: string
                        lat:
                          type: number
                          format: float
                          nullable: true
                        long:
                          type: number
                          format: float
                          nullable: true
                        status:
                          type: string
                        price:
                          type: number
                          format: float
                        area:
                          type: string
                        listing_type:
                          type: string
                          enum: [sale, rent]
                        seller_type:
                          type: string
                          enum: [owner, broker]
                        property_type:
                          type: object
                          properties:
                            id:
                              type: integer
                            name_ar:
                              type: string
                            name_en:
                              type: string
                            icon:
                              type: string
                        user:
                          type: object
                          properties:
                            id:
                              type: integer
                        broker_office:
                          type: object
                          nullable: true
                          properties:
                            id:
                              type: integer
                        created_at:
                          type: string
                          format: date-time
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                      page:
                        type: integer
                      limit:
                        type: integer
                      totalPages:
                        type: integer
        '404':
          description: Properties not found

    post:
      summary: Create a new property
      description: Adds a new property with the provided details.
      tags:
        - property
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title_ar:
                  type: string
                title_en:
                  type: string
                desc_ar:
                  type: string
                desc_en:
                  type: string
                location:
                  type: string
                status:
                  type: string
                price:
                  type: number
                  format: float
                area:
                  type: string
                listing_type:
                  type: string
                  enum: [sale, rent]
                seller_type:
                  type: string
                  enum: [owner, broker]
                property_type_id:
                  type: integer
                broker_office_id:
                  type: integer
                  nullable: true
                lat:
                  type: number
                  format: float
                  nullable: true
                long:
                  type: number
                  format: float
                  nullable: true
                attributes:
                  type: array
                  items:
                    type: object
                    required:
                      - id
                      - value
                    properties:
                      id:
                        type: integer
                        example: 1
                      value:
                        type: string
                        example: "sportage"
                specifications:
                  type: array
                  items:
                    type: object
                    required:
                      - id
                      - value
                    properties:
                      id:
                        type: integer
                        example: 1
                      value:
                        type: string
                        example: "true"
                        images:
                          type: array
                          items:
                            type: string
              required:
                - title_ar
                - title_en
                - location
                - price
                - area
                - listing_type
                - seller_type
                - property_type_id
      responses:
        '201':
          description: Property created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title_ar:
                    type: string
                  title_en:
                    type: string
                  location:
                    type: string
                  status:
                    type: string
                  price:
                    type: number
                    format: float
                  area:
                    type: string
                  listing_type:
                    type: string
                  seller_type:
                    type: string
                  property_type:
                    type: object
                    properties:
                      id:
                        type: integer
                      name_ar:
                        type: string
                      name_en:
                        type: string
                  images:
                    type: array
                    items:
                      type: string
                  created_at:
                    type: string
                    format: date-time
        '400':
          description: Invalid input data
        '403':
          description: Forbidden action (user not authorized to create property)

  /property/{id}:
    get:
      summary: Get a property by ID
      description: Retrieves a property by its unique ID.
      tags:
        - property
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the property to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Successfully retrieved property
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title_ar:
                    type: string
                  title_en:
                    type: string
                  desc_ar:
                    type: string
                  desc_en:
                    type: string
                  isActive:
                    type: boolean
                  location:
                    type: string
                  images:
                    type: array
                    items:
                      type: string
                  lat:
                    type: number
                    format: float
                    nullable: true
                  long:
                    type: number
                    format: float
                    nullable: true
                  status:
                    type: string
                  price:
                    type: number
                    format: float
                  area:
                    type: string
                  listing_type:
                    type: string
                    enum: [sale, rent]
                  seller_type:
                    type: string
                    enum: [owner, broker]
                  property_type:
                    type: object
                    properties:
                      id:
                        type: integer
                      name_ar:
                        type: string
                      name_en:
                        type: string
                      icon:
                        type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                  broker_office:
                    type: object
                    nullable: true
                    properties:
                      id:
                        type: integer
                  created_at:
                    type: string
                    format: date-time
        '404':
          description: Property not found

    put:
      summary: Update an existing property
      description: Updates the details of an existing property.
      tags:
        - property
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the property to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title_ar:
                  type: string
                title_en:
                  type: string
                desc_ar:
                  type: string
                desc_en:
                  type: string
                isActive:
                  type: boolean
                location:
                  type: string
                status:
                  type: string
                price:
                  type: number
                  format: float
                area:
                  type: string
                listing_type:
                  type: string
                  enum: [sale, rent]
                seller_type:
                  type: string
                  enum: [owner, broker]
                property_type_id:
                  type: integer
                broker_office_id:
                  type: integer
                  nullable: true
                lat:
                  type: number
                  format: float
                  nullable: true
                long:
                  type: number
                  format: float
                  nullable: true
                images:
                  type: array
                  items:
                    type: string
                keptImages:
                  description: A JSON array of the paths to images that should be kept
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Property updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title_ar:
                    type: string
                  title_en:
                    type: string
                  location:
                    type: string
                  status:
                    type: string
                  price:
                    type: number
                    format: float
                  area:
                    type: string
                  listing_type:
                    type: string
                  seller_type:
                    type: string
                  property_type:
                    type: object
                    properties:
                      id:
                        type: integer
                      name_ar:
                        type: string
                      name_en:
                        type: string
                  images:
                    type: array
                    items:
                      type: string
                  updated_at:
                    type: string
                    format: date-time
        '404':
          description: Property not found
        '403':
          description: Forbidden action (user not authorized to update property)

    delete:
      summary: Delete a property
      description: Deletes a property by ID.
      tags:
        - property
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the property to delete
          schema:
            type: integer
      responses:
        '200':
          description: Property deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Property not found
        '403':
          description: Forbidden action (user not authorized to delete property)

  /property-types:
    get:
      summary: Get list of property types
      tags:
        - property
      responses:
        '200':
          description: Successfully retrieved property types
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name_ar:
                      type: string
                    name_en:
                      type: string
                    icon:
                      type: string
                    created_at:
                      type: string
                      format: date-time
        '404':
          description: Property types not found

components:
  schemas:
    Property:
      type: object
      properties:
        id:
          type: integer
        title_ar:
          type: string
        title_en:
          type: string
        desc_ar:
          type: string
        desc_en:
          type: string
        isActive:
          type: boolean
        location:
          type: string
        images:
          type: array
          items:
            type: string
        lat:
          type: number
          format: float
          nullable: true
        long:
          type: number
          format: float
          nullable: true
        status:
          type: string
        price:
          type: number
          format: float
        area:
          type: string
        listing_type:
          type: string
          enum: [sale, rent]
        seller_type:
          type: string
          enum: [owner, broker]
        created_at:
          type: string
          format: date-time

    PropertyType:
      type: object
      properties:
        id:
          type: integer
        name_ar:
          type: string
        name_en:
          type: string
        icon:
          type: string
        created_at:
          type: string
          format: date-time